---
title: "Analysis"
author: "TR"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r packages, include=FALSE}
library(tidyverse)
library(ggplot2)
library(knitr)
library(lubridate)
library(data.table)
library(ggpubr)
library(lme4)
library(nlme)
library(lmerTest)
library(emmeans)
library(MuMIn)
library(visreg)
library(car)
library(sjPlot)
library(zoo)
library(viridis)
```

```{r divide SIMS data into years, include=FALSE, echo=FALSE, eval=FALSE}
rm(list = ls())

#Read newest annu file
annu <- read.delim("Data/2021_annuli_with_rad.txt", header = T, stringsAsFactors = F, sep = "\t", dec = ".")


#load SIMS data
sims <- fread("Data/Otolith_data_anadromous_2021_clean_core_with_distance_um.csv")
names(sims) <- tolower(names(sims))

#inverse order for distances
sims <- sims %>% group_by(id)%>%arrange(distance_um, by_group = F)%>%ungroup()%>%
  arrange(id)

#remove 34
#sims <- sims[grepl("34", sims$id)==F,]

#select Pilot fish
sims <- sims%>%filter(id%in%unique(annu$simsID)==TRUE)

#fish list
PikeDB <- read.delim("C:/Users/timor/Nextcloud2/Boddenhecht/Data/Pike Data/1.pike_data_base_FOR_USERS/1Pike_Latest_Version.txt", 
                     sep = ";", dec = ".", header = T, stringsAsFactors = F)
fishdata <- PikeDB%>%
  transmute(fishID=case_when(Fish_ID=="BH-91050.2"~"BH-91050",
                             Fish_ID=="BH-51614"&Waterbody=="BAT"~"NA",
                         TRUE~Fish_ID),
            cdate=Date,
            TL_mm = Total_Length_mm,
            Weight=Weight,
            sex=Sex,
            area=Waterbody)

#correct annu placement
# ID <-"BH-93178"
# x <- 1
# y <- 10

# annu[annu$fishID == ID & annu$year == x,]$rad_um <- annu[annu$fishID == ID & annu$year == x,]$rad_um+y
# annu[annu$fishID == ID & annu$year == x,]$increment_um <- annu[annu$fishID == ID & annu$year == x,]$increment_um+y

#If you need to change the age of a fish
# annu[annu$fishID == ID & annu$year == 2,]$rad_um <- annu[annu$fishID == ID & annu$year == 2,]$rad_um
# annu[annu$fishID == ID & annu$year == 2,]$increment_um <- annu[annu$fishID == ID & annu$year == 2,]$increment_um+annu[annu$fishID == ID & annu$year == 1,]$increment_um
# 
# annu[annu$fishID == ID & annu$year == 2,]$year <- 1
# annu[annu$fishID == ID & annu$yearclass == 2,]$yearclass <- 1
# 
# annu[annu$fishID == ID & annu$year == 3,]$year <- 2
# annu[annu$fishID == ID & annu$yearclass == 3,]$yearclass <- 2
# 
# annu[annu$fishID == ID & annu$year == 4,]$year <- 3
# annu[annu$fishID == ID & annu$yearclass == 4,]$yearclass <- 3
# 
# annu[annu$fishID == ID & annu$year == 5,]$year <- 4
# annu[annu$fishID == ID & annu$yearclass == 5,]$yearclass <- 4
# 
# annu[annu$fishID == ID & annu$year == 6,]$year <- 5
# annu[annu$fishID == ID & annu$yearclass == 6,]$yearclass <- 5
# 
# annu[annu$fishID == ID & annu$year == 7,]$year <- 6
# annu[annu$fishID == ID & annu$yearclass == 7,]$yearclass <- 6
# 
# annu[annu$fishID == ID,]$age <- 5

#Loop to break into years
IDpike <- unique(sims$id)
radID <- unique(annu$year)
y <- NULL
yy <- NULL

for (i in 1:length(IDpike)) {
  for (j in 0:length(annu[which(annu$simsID==IDpike[i]), "year"])) {
y <- ifelse(sims[which(sims$id==IDpike[i]), "distance_um"]<=
                      annu[which(annu$simsID==IDpike[i]&annu$year==radID[j]), "rad_um"]&
              sims[which(sims$id==IDpike[i]), "distance_um"]
              >=annu[which(annu$simsID==IDpike[i]&annu$year==radID[j-1]), "rad_um"],
                    annu[which(annu$simsID==IDpike[i]&annu$year==radID[j]), "year"],
            ifelse(sims[which(sims$id==IDpike[i]), "distance_um"]>
              max(annu[which(annu$simsID==IDpike[i]), "rad_um"])&
                radID[j]==max(annu[which(annu$simsID==IDpike[i]), "year"]), 
            max(annu[which(annu$simsID==IDpike[i]), "year"]),NA))
yy <- c(yy, na.omit(y))
  }
}

##revert the order of distances in "sims", so the yy vector can be pasted correctly

str_sort(unique(sims$id))
str_sort(unique(annu$simsID))

sims$year <- yy

#prepare join with pike data
sims2 <- sims%>%
  group_by(id)%>%
  ungroup()%>%
  transmute(simsID = id,
            OH=oh,
            d18O = d18o,
            distance_um = distance_um,
            year = year)

pikedata <- annu%>%
  inner_join(sims2, by = c("simsID", "year"))

pikedata_all <- pikedata%>%
  inner_join(fishdata, by = "fishID")

pike_d18O <- pikedata_all%>%
  transmute(ID = fishID,
            TL_mm = TL_mm,
            weight = Weight,
            sex = sex,
            area = area,
            capt_date = cdate,
            age = age,
            cohort = cohort,
            year = year,
            inc_um = increment_um,
            rad_um = rad_um,
            core = core,
            OH=OH,
            d18O = d18O,
            sims_dist = distance_um)

#OH plots
IDOto <- unique(pike_d18O$ID)

for (i in 1:length(IDOto)) {
  png(paste0("Figures/Test_plots/", IDOto[i], "_OH.png"))
  plot(pike_d18O[which(pike_d18O$ID == IDOto[i]), "sims_dist",], 
       pike_d18O[which(pike_d18O$ID == IDOto[i]), "OH",], main = "", 
       xlab =  "", ylab = "", xlim = c(0, max(pike_d18O[which(pike_d18O$ID == IDOto[i]), "sims_dist",], na.rm = T)), 
       col.axis = "black", cex.axis = 1.7, type = "b", col = "black", lwd = 2, fg = "black", cex = 1, axes = T, pch = 19)
  abline(v = c(pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 1), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 2), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 3), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 4), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 5), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 6), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 7), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 8), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 9), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 10), "rad_um"],
               pike_d18O[which(pike_d18O$ID == IDOto[i]&
                             pike_d18O$year == 11), "rad_um"])) 
  title(main = "", ylab = "d18O", cex.lab = 15, col.lab = "black", line = 30)
  dev.off()  
}

#save annu as table to change the distances
fwrite(pike_d18O, "Data/2021_anadromous_data_clean.csv")
```

```{r join data together, include=FALSE, eval=FALSE}
rm(list = ls())
Oto_2021_ana <- fread("Data/2021_anadromous_data_clean.csv")
Oto_2021_main <- fread("Data/2021_main_data_clean.csv")
Oto_2022_main <- fread("Data/2022_data_clean.csv")

Otoall <- rbind(Oto_2021_ana, Oto_2021_main, Oto_2022_main)

fwrite(Otoall, "Data/Oto_all_clean_with_distance_year.csv")
```

```{r join data to Sr, include=FALSE, eval=FALSE}
rm(list = ls())

Oto_d18O <- fread("Data/Oto_all_clean_with_distance_year.csv")

LA <- fread("Data/Pike-LA-ICPMS-years_whole-sample_with-TL.txt")

LA_clean <- LA%>%
  filter(LA_dist>=50)%>%
  filter(comment=="OK")%>%
  transmute(ID = fishID,
            age=age,
            capt = area,
            area = case_when(area %in% "Peene" ~ "Tributary",
                             area %in% "Barthe" ~ "Tributary",
                             area %in% "NHG" ~ "Tributary",
                             area %in% "Sehrowbach" ~ "Tributary",
                             area %in% "Bandycksgraben" ~ "Tributary",
                             area %in% "Ziese" ~ "Tributary",
                             area %in% "KB" ~ "Lagoon",
                             area %in% "SB" ~ "Lagoon",
                             area %in% "WB" ~ "Lagoon",
                             area %in% "BEG" ~ "Lagoon", 
                             area %in% "KJB" ~ "Lagoon",
                             area %in% "GJB" ~ "Lagoon",
                             area %in% "GB" ~ "Lagoon",
                             area %in% "KD" ~ "Lake",
                             TRUE ~ "NA"),
            Sr = Sr,
            Na = Na,
            Mg = Mg,
            Ba = Ba,
            Mn = Mn,
            LA_dist = LA_dist,
            lifeyear=lifeyear)

#Smooth trace element data to remove noise
LA_smooth <- LA_clean%>%group_by(ID)%>%
  transmute(ID=ID,
            age=age,
            capt=capt,
            area=area,
            Sr=as.numeric(zoo::rollmean(Sr, k=9, fill=NA, align = "left")),
            Na=as.numeric(zoo::rollmean(Na, k=9, fill=NA, align = "left")),
            Mg=as.numeric(zoo::rollmean(Mg, k=9, fill=NA, align = "left")),
            Ba=as.numeric(zoo::rollmean(Ba, k=9, fill=NA, align = "left")),
            Mn=as.numeric(zoo::rollmean(Mn, k=9, fill=NA, align = "left")),
            LA_dist=as.numeric(LA_dist),
            lifeyear=lifeyear)

#Order data sets for joining
d18O_clean <- Oto_d18O[order(Oto_d18O$ID),]
LA_smooth <- LA_smooth[order(LA_smooth$ID),]

#Convert to data frame, so approx (), as approx() behaves weird on data tables
d18O_clean <- as.data.frame(d18O_clean)
LA_smooth <- as.data.frame(LA_smooth)

LA_clean <- LA_clean %>% drop_na()

#reinterpolate Sr (higher spatial resolution ~5.5 um) to d18O distances (lower spatial resolution, ~35 um) before joining
IDOto <- unique(d18O_clean$ID)
dfE <- data.frame()
for (i in 1:length(IDOto)) {
  if(IDOto[i]%in%unique(LA_smooth$ID)){
    Sr <- data.frame(approx(LA_smooth[which(LA_smooth$ID==IDOto[i]),"LA_dist"],
              LA_smooth[which(LA_smooth$ID==IDOto[i]),"Sr"],
              n = nrow(d18O_clean[which(d18O_clean$ID==IDOto[i]),]),
              rule = 1, method = "linear", ties = "ordered"))
    df <- as.data.frame(Sr[,2])
  }
  else{
    df <- data.frame(value = rep(NA,nrow(d18O_clean[which(d18O_clean$ID == IDOto[i]),])))
    names(df) <- names(dfE)
  }
  dfE <- rbind(dfE,df)
}


Otoall <- cbind(d18O_clean, dfE)

fwrite(Otoall, "Data/Oto_all_clean_with_distance_year.csv")
```

```{r EMS measurements, include=FALSE, eval=FALSE}
rm(list = ls())

#read in matrices
BH_1855_Ca <- as.matrix(fread("Data/EMS_maps/644_Ca_map.txt"))
BH_1855_Mg <- as.matrix(fread("Data/EMS_maps/644_Mg_map.txt"))
BH_1855_P <- as.matrix(fread("Data/EMS_maps/644_P_map.txt"))
BH_1855_S <- as.matrix(fread("Data/EMS_maps/644_S_map.txt"))
BH_1855_Sr <- as.matrix(fread("Data/EMS_maps/644_Sr_map.txt"))
BH_1588_Ca <- as.matrix(fread("Data/EMS_maps/652_Ca_map.txt"))
BH_1588_Mg <- as.matrix(fread("Data/EMS_maps/652_Mg_map.txt"))
BH_1588_P <- as.matrix(fread("Data/EMS_maps/652_P_map.txt"))
BH_1588_S <- as.matrix(fread("Data/EMS_maps/652_S_map.txt"))
BH_1588_Sr <- as.matrix(fread("Data/EMS_maps/652_Sr_map.txt"))
BH_1722_Ca <- as.matrix(fread("Data/EMS_maps/660_Ca_map.txt"))
BH_1722_Mg <- as.matrix(fread("Data/EMS_maps/660_Mg_map.txt", fill = TRUE))
BH_1722_P <- as.matrix(fread("Data/EMS_maps/660_P_map.txt"))
BH_1722_S <- as.matrix(fread("Data/EMS_maps/660_S_map.txt"))
BH_1722_Sr <- as.matrix(fread("Data/EMS_maps/660_Sr_map.txt"))

#replace 0 with NA
BH_1855_Ca[BH_1855_Ca == 0] <- NA
BH_1855_Mg[BH_1855_Mg == 0] <- NA
BH_1855_P[BH_1855_P == 0] <- NA
BH_1855_S[BH_1855_S == 0] <- NA
BH_1855_Sr[BH_1855_Sr == 0] <- NA
BH_1588_Ca[BH_1588_Ca == 0] <- NA
BH_1588_Mg[BH_1588_Mg == 0] <- NA
BH_1588_P[BH_1588_P == 0] <- NA
BH_1588_S[BH_1588_S == 0] <- NA
BH_1588_Sr[BH_1588_Sr == 0] <- NA
BH_1722_Ca[BH_1722_Ca == 0] <- NA
BH_1722_Mg[BH_1722_Mg == 0] <- NA
BH_1722_P[BH_1722_P == 0] <- NA
BH_1722_S[BH_1722_S == 0] <- NA
BH_1722_Sr[BH_1722_Sr == 0] <- NA

#test with Ca (should be ~ 38)
BH_1855_CA_perc <- ((BH_1855_Ca/80)-1.472)/9.188
BH_1588_CA_perc <- ((BH_1588_Ca/80)-1.472)/9.188
BH_1722_CA_perc <- ((BH_1722_Ca/80)-1.472)/9.188

mean(BH_1855_CA_perc, na.rm = TRUE)
mean(BH_1588_CA_perc, na.rm = TRUE)
mean(BH_1722_CA_perc, na.rm = TRUE)

#Convert the rest
BH_1855_Mg_perc <- ((BH_1855_Mg/80)-3)/18.359
BH_1855_S_perc <- ((BH_1855_S/80)-0.592)/12.8
BH_1855_Sr_perc <- ((BH_1855_Sr/80)-1.093)/3.323
BH_1855_P_perc <- ((BH_1855_P/80)-0.375)/9.039
BH_1588_Mg_perc <- ((BH_1588_Mg/80)-3)/18.359
BH_1588_S_perc <- ((BH_1588_S/80)-0.592)/12.8
BH_1588_Sr_perc <- ((BH_1588_Sr/80)-1.093)/3.323
BH_1588_P_perc <- ((BH_1588_P/80)-0.375)/9.039
BH_1722_Mg_perc <- ((BH_1722_Mg/80)-3)/18.359
BH_1722_S_perc <- ((BH_1722_S/80)-0.592)/12.8
BH_1722_Sr_perc <- ((BH_1722_Sr/80)-1.093)/3.323
BH_1722_P_perc <- ((BH_1722_P/80)-0.375)/9.039

#Mean and range of P and S
range(BH_1855_P_perc, na.rm = TRUE)
range(BH_1588_P_perc, na.rm = TRUE)
range(BH_1722_P_perc, na.rm = TRUE)

range(BH_1855_S_perc, na.rm = TRUE)
range(BH_1588_S_perc, na.rm = TRUE)
range(BH_1722_S_perc, na.rm = TRUE)

range(BH_1855_Mg_perc, na.rm = TRUE)
range(BH_1588_Mg_perc, na.rm = TRUE)
range(BH_1722_Mg_perc, na.rm = TRUE)
```

# Cleanup for modelling

```{r Model start, include=FALSE, eval=FALSE}
rm(list = ls())

Otos <- fread("Data/Oto_all_clean_with_distance_year.csv")
phenos <- fread("Data/Pikedata_model_phenos.csv")

phenos2 <- phenos%>%
  transmute(ID, phenotype)%>%
  distinct()

Otos1 <- Otos%>%
  left_join(phenos2, by = "ID")

head(Otos)
tail(Otos)
str(Otos)

Otos2 <- Otos1%>%
  transmute(ID=ID,
            TL_mm=as.numeric(TL_mm),
            weight=as.numeric(weight),
            sex=case_when(ID == "BH-90307"~"f",
                          TRUE ~ sex),
            area=case_when(area=="SB"~"Lagoon",
                           area=="KB"~"Lagoon",
                           area=="WB"~"Lagoon",
                           area=="BEG"~"Lagoon",
                           area=="KJB"~"Lagoon",
                           area=="GJB"~"Lagoon",
                           area=="GB"~"Lagoon",
                           TRUE~"Tributary"),
            phenotype,
            capt_date=capt_date,
            age=as.factor(age),
            cohort=as.factor(cohort),
            year=as.numeric(year),
            inc_um=inc_um/1000,
            rad_um=rad_um,
            core=core,
            OH=as.numeric(scale(OH)),
            d18O=as.numeric(scale(d18O)),
            Sr=as.numeric(scale(`Sr[, 2]`)),
            sims_dist=sims_dist/1000)%>%
  drop_na(d18O,OH, Sr)%>%
  distinct()

fwrite(Otos2, "Data/Otodata_model.csv")
```

```{r model exploration, include=FALSE, eval=FALSE}
par(mfrow=c(1,2))
dotchart(Otos2$OH, color = Otos2$year, main = "Color = Age")
dotchart(Otos2$OH, color = Otos2$sex, main = "Color = Sex")
dotchart(Otos2$OH, color = Otos2$area, main = "Color = Area")

par(mfrow=c(2,2))
boxplot(Otos2$OH~Otos2$year, ylab ="OH value", xlab = "Age")
boxplot(Otos2$OH~Otos2$area, ylab ="OH value", xlab = "Area")
plot(Otos2$OH~Otos2$d18O, ylab ="OH", xlab = "d18O")
plot(Otos2$OH~Otos2$inc_um, ylab ="OH", xlab = "growth increment")
plot(0, xaxt = 'n', yaxt = 'n', bty = 'n', pch = '', ylab = '', xlab = '')

par(mfrow = c(2,2))
hist(Otos2$inc_um, main = "", xlab = "Increment (um)")
hist(Otos2$OH, main = "", xlab = "OH value")
hist(Otos2$d18O, main = "", xlab = "d18O value")
plot(0, xaxt = 'n', yaxt = 'n', bty = 'n', pch = '', ylab = '', xlab = '')
```

## Initial model
$$\delta^{18}O \sim OH+Sr+Distance+increment+area+Sex+(1|ID)$$

```{r initial model, include=FALSE, eval=FALSE}
rm(list = ls())

Otos2 <- fread("Data/Otodata_model.csv")

Otomodel.1 <- lmer(d18O~OH+sims_dist+inc_um+area+phenotype+sex+(1|ID), REML = T, data = Otos2)

summary(Otomodel.1)
```

```{r variance inflation factors, include=FALSE, eval=FALSE}
Otomodel.1 <- lmer(d18O~OH+Sr+sims_dist+inc_um+area+phenotype+sex+(1|ID), REML = T, data = Otos2)

Oto.vif <- vif(Otomodel.1)

png(filename = "Figures/supplement/VIF-factors.png", width = 5000, height = 2500, res = 600)
barplot(Oto.vif[,1], main = "VIF values", horiz = F, col = "darkgreen", ylim = c(0,6), las = 2)
abline(h = 5, lwd = 3, lty = 2, col="red")
dev.off()
```

```{r test effects, include=FALSE, eval=FALSE}
#Test random effect of ID
rand(Otomodel.1)

#Test main effects
No_OH <- update(Otomodel.1, ~.-OH)
anova(Otomodel.1, No_OH)

No_pheno <- update(Otomodel.1, ~.-phenotype)
anova(Otomodel.1, No_pheno)

No_dist <- update(Otomodel.1, ~.-sims_dist)
anova(Otomodel.1, No_dist)

No_inc <- update(Otomodel.1, ~.-inc_um)
anova(Otomodel.1, No_inc)

No_area <- update(Otomodel.1, ~.-area)
anova(Otomodel.1, No_area)

No_sex <- update(Otomodel.1, ~.-sex)
anova(Otomodel.1, No_sex)

tab_model(Otomodel.1, show.fstat = T, show.loglik = T, digits.re = 20, show.re.var = T)
```

```{r model validation, include=FALSE, eval=FALSE}
Otos2$resid <- resid(Otomodel.1)

png(filename = "Figures/supplement/fitted-vs-resid_plot.png", width = 5000, height = 2500, res = 600)
plot(Otomodel.1, xlab = "Fitted", ylab = "Residuals")
dev.off()

png(filename = "Figures/supplement/resid_hist.png", width = 5000, height = 2500, res = 600)
hist(Otos2$resid, main = "", xlab = "Residuals")
dev.off()

png(filename = "Figures/supplement/resid_qqnorm.png", width = 5000, height = 2500, res = 600)
qqnorm(resid(Otomodel.1))
qqline(resid(Otomodel.1))
dev.off()

png(filename = "Figures/supplement/resid_params.png", width = 5000, height = 2500, res = 600)
par(mfrow=c(2,3))
plot(Otos2$resid~Otos2$OH, ylab = "Residuals", xlab = "OH", las = 2)
plot(Otos2$resid~Otos2$sims_dist, ylab = "Residuals", xlab = "distance to core (um)", las = 2)
plot(Otos2$resid~Otos2$inc_um, ylab = "Residuals", xlab = "increment (um)", las = 2)
plot(Otos2$resid~as.factor(Otos2$area), ylab = "Residuals", xlab = "capture area")
plot(Otos2$resid~as.factor(Otos2$phenotype), ylab = "Residuals", xlab = "behavioral phenotype")
plot(Otos2$resid~as.factor(Otos2$sex), ylab = "Residuals", xlab = "capture area")
dev.off()
```

```{r figures for d18O - OH correlation, include=FALSE, eval=FALSE}
#script to form annual means of elemental data for clustering and increment analysis
rm(list = ls())
#Read in data
Otodata <- fread("Data/Oto_all_clean_with_distance_year.csv")

Otodata2 <- Otodata%>%
  transmute(ID=ID,
            TL_mm=TL_mm,
            weight=weight,
            sex=sex,
            capt_date=capt_date,
            age=as.factor(age),
            capt=area,
            area=case_when(area=="SB"~"Lagoon",
                           area=="KB"~"Lagoon",
                           area=="WB"~"Lagoon",
                           area=="BEG"~"Lagoon",
                           area=="KJB"~"Lagoon",
                           area=="GJB"~"Lagoon",
                           area=="GB"~"Lagoon",
                           area=="Badendycksgraben" ~ "Tributary",
                           area=="NHG" ~ "Tributary",
                           area=="Sehrowbach" ~ "Tributary",
                           area=="Ziese" ~ "Tributary",
                           area=="Barthe" ~ "Tributary",
                           area=="Peene" ~ "Tributary",
                           TRUE~"Control lake"),
            OH=OH,
            d18O=d18O,
            year=as.factor(year),
            inc_um=inc_um,
            rad_um=rad_um,
            dist=sims_dist)

# Plot lifelong increase in d18O --> colder the older
mypallette <- viridis::viridis(4, direction = 1)

d18O <- ggplot(Otodata2[Otodata2$ID!="BH-90910",])+
  geom_point(aes(x = OH, y = d18O, color=area), size = 0.001)+
  geom_smooth(aes(x = OH, y = d18O, color=area),  size=1 , method = "lm")+
  lims(x = c(0.02,0.06))+
  labs(x=expression("OH/"^16*"O count rate ratio"),
       y=expression(delta^18*"O"~("\u2030 VPDB")),
       color="area of capture")+
  theme_classic()+
  scale_color_viridis_d()+
  theme(panel.grid.major = element_line(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(.8,"line"))+
  coord_cartesian(clip = "off")

ggsave("Figures/OH-exploratory-figure.png", d18O, width = 15, height = 10, units = "cm", dpi = 600, bg = "white")
```

```{r figures for d18O - OH overlay to EMS scans, include=FALSE, eval=FALSE}

rm(list = ls())
#Read in data
Otodata <- fread("Data/Oto_all_clean_with_distance_year.csv")

Otodata2 <- Otodata%>%
  transmute(ID=ID,
            TL_mm=TL_mm,
            weight=weight,
            sex=sex,
            capt_date=capt_date,
            age=as.factor(age),
            capt=area,
            area=case_when(area=="SB"~"Lagoon",
                           area=="KB"~"Lagoon",
                           area=="WB"~"Lagoon",
                           area=="BEG"~"Lagoon",
                           area=="KJB"~"Lagoon",
                           area=="GJB"~"Lagoon",
                           area=="GB"~"Lagoon",
                           area=="Badendycksgraben" ~ "Tributary",
                           area=="NHG" ~ "Tributary",
                           area=="Sehrowbach" ~ "Tributary",
                           area=="Ziese" ~ "Tributary",
                           area=="Barthe" ~ "Tributary",
                           area=="Peene" ~ "Tributary",
                           TRUE~"Control lake"),
            OH=OH,
            d18O=d18O,
            year=as.factor(year),
            inc_um=inc_um,
            rad_um=rad_um,
            dist=sims_dist)

BH01855 <- ggplot(Otodata2[Otodata2$ID == "BH-01855",], aes(dist, OH))+
  geom_point(size = 3, color = "black")+
  geom_line(linewidth = 2, color = "black")+
  labs(y = expression("OH/"^16*"O count ratio"),
       x = expression("distance from otolith core"~(mu*"m")))+
  theme_classic()+
  theme(panel.grid.major = element_line(color = "black"),
        panel.grid.minor = element_line(color = "black"),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(size = 1, colour = "black", linetype = 1),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.text = element_text(size = 20, colour = "black"),
        axis.title.x = element_text(size = 20, face = "bold", color = "black"),
        axis.title.y = element_text(size = 20, face = "bold", color = "black",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 20),
        legend.key.size = unit(1,"line"))

ggsave("Figures/supplement/BH-01855-OH.png", BH01855, width = 15, height = 15, units = "cm", dpi = 600, bg = "white")

BH01588 <- ggplot(Otodata2[Otodata2$ID == "BH-01588",], aes(dist, OH))+
  geom_point(size = 3, color = "black")+
  geom_line(linewidth = 2, color = "black")+
  labs(y = expression("OH/"^16*"O count ratio"),
       x = expression("distance from otolith core"~(mu*"m")))+
  theme_classic()+
  theme(panel.grid.major = element_line(color = "black"),
        panel.grid.minor = element_line(color = "black"),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(size = 1, colour = "black", linetype = 1),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.text = element_text(size = 20, colour = "black"),
        axis.title.x = element_text(size = 20, face = "bold", color = "black"),
        axis.title.y = element_text(size = 20, face = "bold", color = "black",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 20),
        legend.key.size = unit(1,"line"))

ggsave("Figures/supplement/BH-01588-OH.png", BH01588, width = 15, height = 15, units = "cm", dpi = 600, bg = "white")

BH01722 <- ggplot(Otodata2[Otodata2$ID == "BH-01722",], aes(dist, OH))+
  geom_point(size = 3, color = "black")+
  geom_line(linewidth = 2, color = "black")+
  labs(y = expression("OH/"^16*"O count ratio"),
       x = expression("distance from otolith core"~(mu*"m")))+
  theme_classic()+
  theme(panel.grid.major = element_line(color = "black"),
        panel.grid.minor = element_line(color = "black"),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        plot.background = element_blank(),
        panel.background = element_blank(),
        axis.line = element_line(size = 1, colour = "black", linetype = 1),
        axis.ticks = element_line(size = 1, colour = "black"),
        axis.text = element_text(size = 20, colour = "black"),
        axis.title.x = element_text(size = 20, face = "bold", color = "black"),
        axis.title.y = element_text(size = 20, face = "bold", color = "black",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 20),
        legend.key.size = unit(1,"line"))

ggsave("Figures/supplement/BH-01722-OH.png", BH01722, width = 15, height = 15, units = "cm", dpi = 600, bg = "white")
```

```{r calculate set of means for temperature reconstruction, include=FALSE, eval=FALSE}
d18OW <- fread("Data/Water_isotopes_Bodden.txt")

d18OW2 <- d18OW%>%
  transmute(waterbody = waterbody,
            area = case_when(waterbody == "Uck"~"Tributary",
                             waterbody == "Peene"~"Tributary",
                             waterbody == "AW"~"P",
                             waterbody == "Ryck"~"Tributary",
                             waterbody == "Beek"~"Tributary",
                             waterbody == "GJB"~"NRB",
                             waterbody == "KJB"~"NRB",
                             waterbody == "BEG"~"NRB",
                             waterbody == "WB"~"NRB",
                             waterbody == "VB"~"WRB",
                             waterbody == "SB"~"WRB",
                             waterbody == "KB"~"WRB",
                             waterbody == "GW"~"WRB",
                             waterbody == "BAT"~"DZB",
                             waterbody == "Barthe"~"Tributary",
                             waterbody == "BoB"~"DZB",
                             waterbody == "SaB"~"DZB",
                             waterbody == "Templer creek"~"Tributary",
                             waterbody == "Recknitz"~"Tributary",
                             waterbody == "ZS"~"DZB",
                             TRUE~waterbody),
            coast.FW = `coast/FW`,
            ID = ID,
            Lat = Lat,
            Long = Long,
            date = Date,
            Sal_PSU = Sal_PSU,
            WT_C = WT_C,
            d18O = d18O,
            SD_d18O = SD_d18O,
            type = type)

d18Osum <- d18OW2%>%
  group_by(area)%>%
  summarise(area=area,
            Sal_PSU=mean(Sal_PSU, na.rm=T),
            WT_C=mean(WT_C, na.rm=T),
            d18O=mean(d18O, na.rm=T),
            Sdd18O=mean(SD_d18O, na.rm=T))%>%
  distinct()

fwrite(d18Osum, "Data/Mean_d18O_areas.csv")
```

```{r prediction of otolith d18O, include=FALSE, eval=FALSE}
rm(list = ls())

#Get isotope data
Isotopes <- fread("Data/Water_isotopes_Bodden.txt")

LUNGdata <- read.delim(file = "Data/LUNGdata_complete.txt", sep = "\t", header = T, stringsAsFactors = F)
LUNGdata_Bodden <- LUNGdata%>%
  filter(type=="Coast")%>%
  mutate(area=case_when(waterbody=="Kubitzer Bodden"~"WRB",
                        waterbody=="Greifswalder Bodden"~"GB",
                        waterbody=="Daenische Wiek"~"GB",
                        waterbody=="Andershofer Bucht"~"GB",
                        waterbody=="Vitter Bodden"~"WRB",
                        waterbody=="Rassower Strom"~"NRB",
                        waterbody=="Breetzer Bodden"~"NRB",
                        waterbody=="Gr. Jasmunder Bodden"~"NRB",
                        waterbody=="Kl. Jasmunder Bodden"~"NRB",
                        waterbody=="Schaproder Bodden"~"WRB",
                        TRUE~"NA"))%>%
  filter(area!="NA")

Lungdata_fresh <- LUNGdata%>%
  filter(type=="Freshwater")%>%
  mutate(area=case_when(waterbody=="Barthe"~"Tributary",
                        waterbody=="Westziese"~"Tributary",
                        waterbody=="Ostziese"~"Tributary",
                        waterbody=="Sehrower Bach"~"Tributary",
                        waterbody=="Badendycksgraben"~"Tributary",
                        TRUE~"NA"))

Bodden_mean <- LUNGdata_Bodden%>%
  group_by(area, year, month)%>%
  dplyr::summarise(area=area,
                   year=year,
                   type=type,
                   SAL=mean(SAL, na.rm=T),
                   WT=mean(WT, na.rm=T))%>%
  distinct()

Fresh_mean <- Lungdata_fresh%>%
  filter(area!="NA")%>%
  group_by(area, year, month)%>%
  dplyr::summarise(area=area,
                   year=year,
                   type=type,
                   SAL=mean(SAL, na.rm=T),
                   WT=mean(WT, na.rm=T))%>%
  distinct()

Isotopes2 <- Isotopes%>%
  transmute(waterbody=waterbody,
            month=month(parse_date_time(Date, "dmy")),
            area=case_when(waterbody=="Uck"~"NA",
                           waterbody=="SH"~"SH",
                           waterbody=="Peene"~"Tributary",
                           waterbody=="P"~"P",
                           waterbody=="AW"~"P",
                           waterbody=="GB"~"GB",
                           waterbody=="Ryck"~"NA",
                           waterbody=="S"~"WRB",
                           waterbody=="Beek"~"NA",
                           waterbody=="GJB"~"NRB",
                           waterbody=="KJB"~"NRB",
                           waterbody=="Baltic"~"Baltic",
                           waterbody=="BEG"~"NRB",
                           waterbody=="WB"~"NRB",
                           waterbody=="VB"~"WRB",
                           waterbody=="SB"~"WRB",
                           waterbody=="KB"~"WRB",
                           waterbody=="GW"~"DZB",
                           waterbody=="BAT"~"DZB",
                           waterbody=="Barthe"~"Tributary",
                           waterbody=="BoB"~"DZB",
                           waterbody=="SaB"~"SaB",
                           waterbody=="Templer creek"~"NA",
                           waterbody=="Recknitz"~"NA",
                           waterbody=="ZS"~"ZS"),
            coast.FW=`coast/FW`,
            d18O=d18O,
            Sal=Sal_PSU,
            WT=WT_C)%>%
  drop_na(d18O)

Isotopes_mean <- Isotopes2%>%
  group_by(month, area)%>%
  dplyr::summarise(month=month,
                   area=area,
                   coast.FW=coast.FW,
                   d18O=mean(d18O, na.rm=T),
                   Sal=mean(Sal, na.rm=T),
                   WT=mean(WT, na.rm=T))%>%
  distinct()

subset.WRB <- subset(Isotopes_mean, area=="WRB")
subset.fresh <- subset(Isotopes_mean, area=="ZS")


#data frame for merging
df <- data.frame(month = 1:12)

#get data for NRB
subset.NRB <- subset(Isotopes_mean, area=="NRB")
#complete months
subset.NRB <- merge(df, subset.NRB, by = "month", all.x = T)
#interpolate between months
subset.NRB$d18O <- na.approx(subset.NRB$d18O, na.rm=F)

#apply linear correction of missing values based on seasonal offset from timeseries
subset.NRB$d18O[1:2] <- subset.WRB$d18O[1:2]/subset.WRB$d18O[3]*subset.NRB$d18O[3]
subset.NRB$d18O[8:12] <- subset.WRB$d18O[8:12]/subset.WRB$d18O[7]*subset.NRB$d18O[7]
subset.NRB$area <- "NRB"

#same for GB area
subset.GB <- subset(Isotopes_mean, area=="GB")
subset.GB <- merge(df, subset.GB, by="month", all.x = T)
subset.GB$d18O <- na.approx(subset.GB$d18O, na.rm=F)

#apply linear correction of missing values based on seasonal offset from timeseries
subset.GB$d18O[1:2] <- subset.WRB$d18O[1:2]/subset.WRB$d18O[3]*subset.GB$d18O[3]
subset.GB$d18O[8:12] <- subset.WRB$d18O[8:12]/subset.WRB$d18O[7]*subset.GB$d18O[7]
subset.GB$area <- "GB"

#tributaries
subset.tributary <- subset(Isotopes_mean, area == "Tributary")
subset.tributary <- merge(df, subset.tributary, by="month", all.x = T)
subset.tributary$d18O <- na.approx(subset.tributary$d18O, na.rm=F)

#apply linear correction of missing values based on seasonal offset from timeseries
subset.tributary$d18O[1:2] <- subset.fresh$d18O[1:2]/subset.fresh$d18O[3]*subset.tributary$d18O[3]
subset.tributary$d18O[8:12] <- subset.fresh$d18O[8:12]/subset.fresh$d18O[7]*subset.tributary$d18O[7]
subset.tributary$area <- "Tributary"

Bodden_iso <- rbind(subset.GB[,c(1,2,4)],subset.WRB[,c(1,2,4)],subset.NRB[,c(1,2,4)])

Fresh_iso <- subset.tributary[,c(1,2,4)]

Bodden_iso_temp <- Bodden_mean%>%left_join(Bodden_iso, by=c("month", "area"))
Fresh_iso_temp <- Fresh_mean%>%left_join(Fresh_iso, by=c("month", "area"))


#Fractionation equation for otolith aragonite
Patterson <- function(month, WT, d18O){
  alpha <- exp((18.56*1000*((WT+273.15)^-1)-33.49)/1000)
  0.97001*(alpha*(1000+d18O)-1000)-29.99
}

Geffen <- function(month, WT, d18O){
  alpha <- exp((15.99*1000*((WT+273.15)^-1)-24.25)/1000)
  0.97001*(alpha*(1000+d18O)-1000)-29.99
}

#calculate theoretical otolith d18O values with prediction intervals
Bodden_iso_oto <- Bodden_iso_temp%>%
  mutate(d18O.oto.Patterson = Patterson(month,WT,d18O),
         d18O.oto.Geffen = Geffen(month,WT,d18O),
         date=as.Date(paste0(year,"-",month,"-","01")))%>%
  group_by(month, year)%>%
  mutate(upper.Pat=max(d18O.oto.Patterson),
         lower.Pat=min(d18O.oto.Patterson),
         upper.Gef=max(d18O.oto.Geffen),
         lower.Gef=min(d18O.oto.Geffen))

Fresh_iso_oto <- Fresh_iso_temp%>%
  mutate(d18O.oto.Patterson = Patterson(month,WT,d18O),
         d18O.oto.Geffen = Geffen(month,WT,d18O),
         date=as.Date(paste0(year,"-",month,"-","01")))%>%
  group_by(month)%>%
  mutate(upper.Pat=max(d18O.oto.Patterson),
         lower.Pat=min(d18O.oto.Patterson),
         upper.Gef=max(d18O.oto.Geffen),
         lower.Gef=min(d18O.oto.Geffen))

fwrite(Bodden_iso_oto, "Data/Bodden_iso_prediction.csv")
fwrite(Fresh_iso_oto, "Data/Tributary_iso_prediction.csv")
```

```{r apply correction, include=FALSE, eval=FALSE}
rm(list = ls())

Otos <- fread("Data/Oto_all_clean_with_distance_year.csv")

Otos2 <- Otos%>%
  filter(area != "KD")%>%
  transmute(ID=ID,
            TL_mm=as.numeric(TL_mm),
            weight=as.numeric(weight),
            sex=case_when(ID == "BH-90307"~"f",
                          TRUE ~ sex),
            area=as.factor(case_when(area == "Sehrowbach"~"anadromous",
                                     area == "Ziese"~"anadromous",
                                     area == "NHG"~"anadromous",
                                     area == "Peene"~"freshwater",
                                     area == "Barthe"~"freshwater",
                                     area == "KB"~"Lagoon",
                                     area == "Badendycksgraben"~"anadromous",
                                     area == "SB"~"Lagoon",
                                     area == "WB"~"Lagoon",
                                     area == "BEG"~"Lagoon",
                                     area == "KJB"~"Lagoon",
                                     area == "GJB"~"Lagoon",
                                     area == "GB"~"Lagoon",
                                     TRUE~area)),
            capt_date,
            age=as.factor(age),
            cohort=cohort,
            year=as.numeric(year),
            inc_um=inc_um,
            OH=OH,
            d18O_Oto=d18O,
            OH=as.numeric(OH),
            Sr=as.numeric(`Sr[, 2]`),
            d18O=as.numeric(d18O),
            sims_dist=sims_dist)%>%
  drop_na(d18O_Oto,OH)%>%
  distinct()

Otos_overview <- Otos2%>%
  transmute(ID, area, sex)%>%
  distinct()

table(Otos_overview$sex, Otos_overview$area)

Otomodel.1 <- lm(d18O~OH, data = Otos2)
summary(Otomodel.1)

intercept_OH <- as.numeric(Otomodel.1$coefficients[2])

Pike_corrected <- Otos2%>%
  transmute(fishID = ID,
            TL_mm = TL_mm,
            weight = weight,
            sex = sex,
            area = area,
            capt_date,
            age = age,
            cohort = cohort,
            year = year,
            OH = OH,
            d18O_oto = d18O_Oto,
            d18O_oto_cor = d18O_Oto-OH*intercept_OH,
            diff = d18O_Oto-d18O_oto_cor,
            sims_dist = sims_dist)

mean(Pike_corrected$diff)
mean(Pike_corrected[Pike_corrected$area=="Lagoon",]$diff)
mean(Pike_corrected[Pike_corrected$area=="freshwater",]$diff)
mean(Pike_corrected[Pike_corrected$area=="anadromous",]$diff)

anova(lm(diff~area, data = Pike_corrected))

fwrite(Pike_corrected, "Data/Oto_corrected.csv")
```

```{r d18O modelling figures, include=FALSE, eval=FALSE}
rm(list = ls())

#Read in data
Pike_corrected <- fread("Data/Oto_corrected.csv")

#Plot raw vs correction
raw_vs_cor <- ggplot(Pike_corrected)+
  geom_smooth(aes(sims_dist, d18O_oto, color = area, fill = area, linetype = "raw"), method = "gam")+
  geom_smooth(aes(sims_dist, d18O_oto_cor, color = area, fill = area, linetype = "correction"), method = "gam")+
  labs(x = expression("distance from otolith core"~(mu*"m")),
       y = expression(delta^18~"O"~("\u2030 VPDB")),
       color = "habitat use",
       fill = "habitat use",
       linetype = "correction")+
  theme_classic()+
  scale_color_viridis_d(direction = 1, begin = 0, end = 0.7)+
  scale_fill_viridis_d(direction = 1, begin = 0, end = 0.7)+
  scale_linetype_manual(breaks = c("raw", "correction"),
                        values = c("solid", "dotted"),
                        guide = guide_legend(override.aes = list(color = "black")))+
  scale_shape_manual(breaks = c("raw", "correction"),
                        values = c(1,2),
                        guide = guide_legend(override.aes = list(color = "black")))+
  theme(panel.grid.major = element_line(),
        panel.grid.minor = element_line(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(1,"line"))

ggsave("Figures/raw_vs_correction.png", raw_vs_cor, width = 15, height = 12, units = "cm", dpi = 600, bg = "white")
```

```{r d18O correction single fish, include=FALSE, eval=FALSE}
rm(list = ls())

#Read in data
Pike_corrected <- fread("Data/Oto_corrected.csv")

BH01855 <- ggplot(Pike_corrected[Pike_corrected$ID=="BH-01855",])+
  geom_point(aes(sims_dist, d18O_oto, color = "raw", shape = "raw"))+
  geom_line(aes(sims_dist, d18O_oto, color = "raw"))+
  geom_point(aes(sims_dist, d18O_oto_cor, color = "correction", shape = "correction"), linetype = "dotted")+
  geom_line(aes(sims_dist, d18O_oto_cor, color = "correction"), linetype = "dotted")+
  scale_color_manual(breaks = c("raw", "correction"),
                     values = viridis(2, begin = 0, end = 0.5))+
  scale_shape_manual(breaks = c("raw", "correction"),
                     values = c(18,19))+
  labs(x = expression("distance from otolith core"~(mu*"m")),
       y = expression(delta^18~"O"~("\u2030 VPDB")),
       color = "",
       shape = "")+
  theme_bw()+
  theme(panel.grid.major = element_line(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(1,"line"))

BH01588 <- ggplot(Pike_corrected[Pike_corrected$ID=="BH-01588",])+
  geom_point(aes(sims_dist, d18O_oto, color = "raw", shape = "raw"))+
  geom_line(aes(sims_dist, d18O_oto, color = "raw"))+
  geom_point(aes(sims_dist, d18O_oto_cor, color = "correction", shape = "correction"), linetype = "dotted")+
  geom_line(aes(sims_dist, d18O_oto_cor, color = "correction"), linetype = "dotted")+
  scale_color_manual(breaks = c("raw", "correction"),
                     values = viridis(2, begin = 0, end = 0.5))+
  scale_shape_manual(breaks = c("raw", "correction"),
                     values = c(18,19))+
  labs(x = expression("distance from otolith core"~(mu*"m")),
       y = expression(delta^18~"O"~("\u2030 VPDB")),
       color = "",
       shape = "")+
  theme_bw()+
  theme(panel.grid.major = element_line(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(1,"line"))

BH01722 <- ggplot(Pike_corrected[Pike_corrected$ID=="BH-01722",])+
  geom_point(aes(sims_dist, d18O_oto, color = "raw", shape = "raw"))+
  geom_line(aes(sims_dist, d18O_oto, color = "raw"))+
  geom_point(aes(sims_dist, d18O_oto_cor, color = "correction", shape = "correction"), linetype = "dotted")+
  geom_line(aes(sims_dist, d18O_oto_cor, color = "correction"), linetype = "dotted")+
  scale_color_manual(breaks = c("raw", "correction"),
                     values = viridis(2, begin = 0, end = 0.5))+
  scale_shape_manual(breaks = c("raw", "correction"),
                     values = c(18,19))+
  labs(x = expression("distance from otolith core"~(mu*"m")),
       y = expression(delta^18~"O"~("\u2030 VPDB")),
       color = "",
       shape = "")+
  theme_bw()+
  theme(panel.grid.major = element_line(),
        legend.background = element_blank(),
        legend.box.background = element_blank(),
        axis.line = element_line(size = .5, colour = "black", linetype = 1),
        axis.ticks = element_line(size = .5, colour = "black"),
        axis.text = element_text(size = 10, colour = "black"),
        axis.title.x = element_text(size = 10, face = "bold"),
        axis.title.y = element_text(size = 10, face = "bold",
                                    margin = margin(r=15)),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10, face = "bold"),
        legend.key.size = unit(1,"line"))

Allplot <- ggarrange(BH01855, BH01588, BH01722, common.legend = T, nrow = 3)

ggsave("Figures/raw-vs-corrected_ind.png", width = 15, height = 30, units = "cm", dpi = 600, bg = "white")
```

#Validation of correction

```{r prediction of otolith d18O, include=FALSE, eval=FALSE}
#script to interpolate water d18O over years observed in pike otoliths
rm(list = ls())

#Get isotope data
Isotopes <- fread("Data/Water_isotopes_Bodden.txt")

LUNGdata <- read.delim(file = "Data/LUNGdata_complete.txt", sep = "\t", header = T, stringsAsFactors = F)
LUNGdata_Bodden <- LUNGdata%>%
  filter(type=="Coast")%>%
  mutate(area=case_when(waterbody=="Kubitzer Bodden"~"WRB",
                        waterbody=="Greifswalder Bodden"~"GB",
                        waterbody=="Daenische Wiek"~"GB",
                        waterbody=="Andershofer Bucht"~"GB",
                        waterbody=="Vitter Bodden"~"WRB",
                        waterbody=="Rassower Strom"~"NRB",
                        waterbody=="Breetzer Bodden"~"NRB",
                        waterbody=="Gr. Jasmunder Bodden"~"NRB",
                        waterbody=="Kl. Jasmunder Bodden"~"NRB",
                        waterbody=="Schaproder Bodden"~"WRB",
                        TRUE~"NA"))%>%
  filter(area!="NA")

Lungdata_fresh <- LUNGdata%>%
  filter(type=="Freshwater")%>%
  mutate(area=case_when(waterbody=="Barthe"~"Tributary",
                        waterbody=="Westziese"~"Tributary",
                        waterbody=="Ostziese"~"Tributary",
                        waterbody=="Sehrower Bach"~"Tributary",
                        waterbody=="Badendycksgraben"~"Tributary",
                        TRUE~"NA"))

Bodden_mean <- LUNGdata_Bodden%>%
  group_by(area, year, month)%>%
  dplyr::summarise(area=area,
                   year=year,
                   type=type,
                   SAL=mean(SAL, na.rm=T),
                   WT=mean(WT, na.rm=T))%>%
  distinct()

Fresh_mean <- Lungdata_fresh%>%
  filter(area!="NA")%>%
  group_by(area, year, month)%>%
  dplyr::summarise(area=area,
                   year=year,
                   type=type,
                   SAL=mean(SAL, na.rm=T),
                   WT=mean(WT, na.rm=T))%>%
  distinct()

Isotopes2 <- Isotopes%>%
  transmute(waterbody=waterbody,
            month=month(parse_date_time(Date, "dmy")),
            area=case_when(waterbody=="Uck"~"NA",
                           waterbody=="SH"~"SH",
                           waterbody=="Peene"~"Tributary",
                           waterbody=="P"~"P",
                           waterbody=="AW"~"P",
                           waterbody=="GB"~"GB",
                           waterbody=="Ryck"~"NA",
                           waterbody=="S"~"WRB",
                           waterbody=="Beek"~"NA",
                           waterbody=="GJB"~"NRB",
                           waterbody=="KJB"~"NRB",
                           waterbody=="Baltic"~"Baltic",
                           waterbody=="BEG"~"NRB",
                           waterbody=="WB"~"NRB",
                           waterbody=="VB"~"WRB",
                           waterbody=="SB"~"WRB",
                           waterbody=="KB"~"WRB",
                           waterbody=="GW"~"DZB",
                           waterbody=="BAT"~"DZB",
                           waterbody=="Barthe"~"Tributary",
                           waterbody=="BoB"~"DZB",
                           waterbody=="SaB"~"SaB",
                           waterbody=="Templer creek"~"NA",
                           waterbody=="Recknitz"~"NA",
                           waterbody=="ZS"~"ZS"),
            coast.FW=`coast/FW`,
            d18O=d18O,
            Sal=Sal_PSU,
            WT=WT_C)%>%
  drop_na(d18O)

Isotopes_mean <- Isotopes2%>%
  group_by(month, area)%>%
  dplyr::summarise(month=month,
                   area=area,
                   coast.FW=coast.FW,
                   d18O=mean(d18O, na.rm=T),
                   Sal=mean(Sal, na.rm=T),
                   WT=mean(WT, na.rm=T))%>%
  distinct()

subset.WRB <- subset(Isotopes_mean, area=="WRB")
subset.fresh <- subset(Isotopes_mean, area=="ZS")


#data frame for merging
df <- data.frame(month = 1:12)

#get data for NRB
subset.NRB <- subset(Isotopes_mean, area=="NRB")
#complete months
subset.NRB <- merge(df, subset.NRB, by = "month", all.x = T)
#interpolate between months
subset.NRB$d18O <- na.approx(subset.NRB$d18O, na.rm=F)

#apply linear correction of missing values based on seasonal offset from timeseries
subset.NRB$d18O[1:2] <- subset.WRB$d18O[1:2]/subset.WRB$d18O[3]*subset.NRB$d18O[3]
subset.NRB$d18O[8:12] <- subset.WRB$d18O[8:12]/subset.WRB$d18O[7]*subset.NRB$d18O[7]
subset.NRB$area <- "NRB"

#same for GB area
subset.GB <- subset(Isotopes_mean, area=="GB")
subset.GB <- merge(df, subset.GB, by="month", all.x = T)
subset.GB$d18O <- na.approx(subset.GB$d18O, na.rm=F)

#apply linear correction of missing values based on seasonal offset from timeseries
subset.GB$d18O[1:2] <- subset.WRB$d18O[1:2]/subset.WRB$d18O[3]*subset.GB$d18O[3]
subset.GB$d18O[8:12] <- subset.WRB$d18O[8:12]/subset.WRB$d18O[7]*subset.GB$d18O[7]
subset.GB$area <- "GB"

#tributaries
subset.tributary <- subset(Isotopes_mean, area == "Tributary")
subset.tributary <- merge(df, subset.tributary, by="month", all.x = T)
subset.tributary$d18O <- na.approx(subset.tributary$d18O, na.rm=F)

#apply linear correction of missing values based on seasonal offset from timeseries
subset.tributary$d18O[1:2] <- subset.fresh$d18O[1:2]/subset.fresh$d18O[3]*subset.tributary$d18O[3]
subset.tributary$d18O[8:12] <- subset.fresh$d18O[8:12]/subset.fresh$d18O[7]*subset.tributary$d18O[7]
subset.tributary$area <- "Tributary"

Bodden_iso <- rbind(subset.GB[,c(1,2,4)],subset.WRB[,c(1,2,4)],subset.NRB[,c(1,2,4)])

Fresh_iso <- subset.tributary[,c(1,2,4)]

Bodden_iso_temp <- Bodden_mean%>%left_join(Bodden_iso, by=c("month", "area"))
Fresh_iso_temp <- Fresh_mean%>%left_join(Fresh_iso, by=c("month", "area"))


#Fractionation equation for otolith aragonite
Patterson <- function(month, WT, d18O){
  alpha <- exp((18.56*1000*((WT+273.15)^-1)-33.49)/1000)
  0.97001*(alpha*(1000+d18O)-1000)-29.99
}

Geffen <- function(month, WT, d18O){
  alpha <- exp((15.99*1000*((WT+273.15)^-1)-24.25)/1000)
  0.97001*(alpha*(1000+d18O)-1000)-29.99
}

#calculate theoretical otolith d18O values with prediction intervals
Bodden_iso_oto <- Bodden_iso_temp%>%
  mutate(d18O.oto.Patterson = Patterson(month,WT,d18O),
         d18O.oto.Geffen = Geffen(month,WT,d18O),
         date=as.Date(paste0(year,"-",month,"-","01")))%>%
  group_by(month, year)%>%
  mutate(upper.Pat=max(d18O.oto.Patterson),
         lower.Pat=min(d18O.oto.Patterson),
         upper.Gef=max(d18O.oto.Geffen),
         lower.Gef=min(d18O.oto.Geffen))

Fresh_iso_oto <- Fresh_iso_temp%>%
  mutate(d18O.oto.Patterson = Patterson(month,WT,d18O),
         d18O.oto.Geffen = Geffen(month,WT,d18O),
         date=as.Date(paste0(year,"-",month,"-","01")))%>%
  group_by(month)%>%
  mutate(upper.Pat=max(d18O.oto.Patterson),
         lower.Pat=min(d18O.oto.Patterson),
         upper.Gef=max(d18O.oto.Geffen),
         lower.Gef=min(d18O.oto.Geffen))

fwrite(Bodden_iso_oto, file = "Data/Bodden-isotope-predictions.csv")
fwrite(Fresh_iso_oto, file = "Data/Freshwater-isotope-predictions.csv")
```

```{r pike data for d18O years, include=FALSE, eval=FALSE}
#script to interpolate pike otolith d18O into yearly (12-month) format
rm(list = ls())

source("Interpolation_function.R")

#Get pike data
Pike <- fread("Data/Oto_corrected.csv")

Pike2 <- Pike%>%
  group_by(fishID)%>%
  mutate(lifeyear = cohort+year)%>%
  drop_na(d18O_oto)

#subset pike according to lifeyears as read
Pike.1 <- subset(Pike2[Pike2$age>=1,], year==1)
Pike.2 <- subset(Pike2[Pike2$age>=2,], year==2)
Pike.3 <- subset(Pike2[Pike2$age>=3,], year==3)
Pike.4 <- subset(Pike2[Pike2$age>=4,], year==4)
Pike.5 <- subset(Pike2[Pike2$age>=5,], year==5)
Pike.6 <- subset(Pike2[Pike2$age>=6,], year==6)
Pike.7 <- subset(Pike2[Pike2$age>=7,], year==7)
Pike.8 <- subset(Pike2[Pike2$age>=8,], year==8)
Pike.9 <- subset(Pike2[Pike2$age>=9,], year==9)
Pike.10 <- subset(Pike2[Pike2$age>=10,], year==10)

Pike_year1_d18O <- interpol(series = Pike.1, length = 12, element = "d18O_oto")
Pike_year2_d18O <- interpol(series = Pike.2, length = 12, element = "d18O_oto")
Pike_year3_d18O <- interpol(series = Pike.3, length = 12, element = "d18O_oto")
Pike_year4_d18O <- interpol(series = Pike.4, length = 12, element = "d18O_oto")
Pike_year5_d18O <- interpol(series = Pike.5, length = 12, element = "d18O_oto")
Pike_year6_d18O <- interpol(series = Pike.6, length = 12, element = "d18O_oto")
Pike_year7_d18O <- interpol(series = Pike.7, length = 12, element = "d18O_oto")
Pike_year8_d18O <- interpol(series = Pike.8, length = 12, element = "d18O_oto")
Pike_year9_d18O <- interpol(series = Pike.9, length = 12, element = "d18O_oto")
Pike_year10_d18O <- interpol(series = Pike.10, length = 12, element = "d18O_oto")

Pike_year1_d18O_cor <- interpol(series = Pike.1, length = 12, element = "d18O_oto_cor")
Pike_year2_d18O_cor <- interpol(series = Pike.2, length = 12, element = "d18O_oto_cor")
Pike_year3_d18O_cor <- interpol(series = Pike.3, length = 12, element = "d18O_oto_cor")
Pike_year4_d18O_cor <- interpol(series = Pike.4, length = 12, element = "d18O_oto_cor")
Pike_year5_d18O_cor <- interpol(series = Pike.5, length = 12, element = "d18O_oto_cor")
Pike_year6_d18O_cor <- interpol(series = Pike.6, length = 12, element = "d18O_oto_cor")
Pike_year7_d18O_cor <- interpol(series = Pike.7, length = 12, element = "d18O_oto_cor")
Pike_year8_d18O_cor <- interpol(series = Pike.8, length = 12, element = "d18O_oto_cor")
Pike_year9_d18O_cor <- interpol(series = Pike.9, length = 12, element = "d18O_oto_cor")
Pike_year10_d18O_cor <- interpol(series = Pike.10, length = 12, element = "d18O_oto_cor")

Pike_year1_d18O$year <- 1
Pike_year2_d18O$year <- 2
Pike_year3_d18O$year <- 3
Pike_year4_d18O$year <- 4
Pike_year5_d18O$year <- 5
Pike_year6_d18O$year <- 6
Pike_year7_d18O$year <- 7
Pike_year8_d18O$year <- 8
Pike_year9_d18O$year <- 9
Pike_year10_d18O$year <- 10

Pike_year1_d18O_cor$year <- 1
Pike_year2_d18O_cor$year <- 2
Pike_year3_d18O_cor$year <- 3
Pike_year4_d18O_cor$year <- 4
Pike_year5_d18O_cor$year <- 5
Pike_year6_d18O_cor$year <- 6
Pike_year7_d18O_cor$year <- 7
Pike_year8_d18O_cor$year <- 8
Pike_year9_d18O_cor$year <- 9
Pike_year10_d18O_cor$year <- 10

Pikeyears_d18O <- rbind(Pike_year1_d18O, Pike_year2_d18O, Pike_year3_d18O, Pike_year4_d18O, Pike_year5_d18O, 
                        Pike_year6_d18O, Pike_year7_d18O, Pike_year8_d18O, Pike_year9_d18O, Pike_year10_d18O)

Pikeyears_d18O_cor <- rbind(Pike_year1_d18O_cor, Pike_year2_d18O_cor, Pike_year3_d18O_cor, Pike_year4_d18O_cor, Pike_year5_d18O_cor, 
                        Pike_year6_d18O_cor, Pike_year7_d18O_cor, Pike_year8_d18O_cor, Pike_year9_d18O_cor, Pike_year10_d18O_cor)

Pikeyears_all <- Pikeyears_d18O%>%
  left_join(Pikeyears_d18O_cor, by = c("fishID", "month", "year"))%>%
  transmute(fishID, year, month,
            d18O = value.x,
            d18O_cor = value.y)

Pikeyears2 <- Pike2%>%
  inner_join(Pikeyears_all, by = c("fishID", "year"))%>%
  transmute(fishID=fishID,
            capt_date=capt_date,
            area=case_when(area == "anadromous" ~ "freshwater",
                           TRUE ~ area),
            age=age,
            cohort=cohort,
            lifeyear=lifeyear,
            month=month,
            year=lifeyear,
            d18O=d18O,
            d18O_cor = d18O_cor,
            date=as.Date(paste0(lifeyear,"-",month,"-","01")))%>%
  distinct()

Pikeyears3 <- Pikeyears2%>%
  group_by(area, date)%>%
  summarise(cohort=cohort,
            month=month,
            d18O=mean(d18O),
            d18O_cor=mean(d18O_cor))%>%
  distinct()

fwrite(Pikeyears3, file = "Data/Pike-d18O-years-interpolated.csv")
```

```{r d18O modelling figures, include=FALSE, eval=FALSE}
#Plotting temperature, predicted otolith d18O and observed otolith d18O
rm(list = ls())

#read in data
Bodden_iso_oto <- fread("Data/Bodden-isotope-predictions.csv")
Fresh_iso_oto <- fread("Data/Freshwater-isotope-predictions.csv")
Pikeyears <- fread("Data/Pike-d18O-years-interpolated.csv")

#plot temperature
Temperature <- ggplot()+
  geom_line(data = Bodden_iso_oto, aes(x = date, y = WT, color=area), size = 1)+
  geom_line(data = Fresh_iso_oto, aes(x = date, y = WT, color=area), size = 1)+
  geom_vline(xintercept = as.Date(c("2008-12-01","2009-12-01","2010-12-01","2011-12-01","2012-12-01","2013-12-01","2014-12-01","2015-12-01",
                          "2016-12-01","2017-12-01","2018-12-01","2019-12-01","2020-12-01","2021-12-01","2022-12-01")), alpha = .5,
             linetype = "dotted")+
  scale_fill_manual(breaks = c("Lagoon", "Tributary"), 
                     values = c("#7570B3","#66A61E"), 
                     labels = c("Lagoon prediction", "Tributary prediction"))+
  scale_color_manual(breaks = c("GB", "NRB", "WRB", "Tributary"),
                     values = c("#C5D86D","#AF3800","#004643","#00BFB2"))+
  scale_x_date(breaks = as.Date(c("2008-01-01","2009-01-01","2010-01-01","2011-01-01","2012-01-01","2013-01-01","2014-01-01","2015-01-01",
                          "2016-01-01","2017-01-01","2018-01-01","2019-01-01","2020-01-01","2021-01-01","2022-01-01")),
               labels = c(as.character(c(2008:2022))),
               limits = c(min(Pikeyears$date), max(Pikeyears$date)))+
  labs(y = "Water temperature (C)",
       color = "area: ")+
  theme_classic()+theme(panel.grid.major.y = element_line(size = .3),
        panel.border = element_rect(fill = NA, linewidth = .3),
        plot.margin = margin(c(20,10,1,1)),
        axis.text.x = element_text(color = "transparent", size = 15, angle = 90),
        axis.text.y = element_text(color = "black", size = 15),
        axis.ticks.x = element_line(colour = "transparent"),
        axis.ticks.y = element_line(linewidth = 0.3),
        axis.ticks.length.y = unit(0.05, "cm"),
        axis.title.x = element_text(size = 15, color = "transparent"),
        axis.title.y = element_text(size = 15, color = "black"),
        axis.line = element_line(linewidth = 0.3),
        legend.text = element_text(size = 15, color = "black"),
        legend.title = element_text(size = 15, color = "black"),
        legend.position = "bottom")

#Plot isotope predictions
Isotopes <- ggplot()+
  geom_line(data = Bodden_iso_oto, aes(x = date, y = d18O, color="d18O"), size = 1)+
  geom_ribbon(data = Bodden_iso_oto, aes(x = date, ymin = lower.Pat, ymax = upper.Pat, fill = "Lagoon"), alpha = 0.3)+
  geom_ribbon(data = Bodden_iso_oto, aes(x = date, ymin = lower.Gef, ymax = upper.Gef, fill = "Lagoon"), alpha = 0.3)+
  geom_ribbon(data = Fresh_iso_oto, aes(x = date, ymin = lower.Pat, ymax = upper.Pat, fill = "Tributary"), alpha = 0.3)+
  geom_ribbon(data = Fresh_iso_oto, aes(x = date, ymin = lower.Gef, ymax = upper.Gef, fill = "Tributary"), alpha = 0.3)+
  geom_vline(xintercept = as.Date(c("2008-12-01","2009-12-01","2010-12-01","2011-12-01","2012-12-01","2013-12-01","2014-12-01","2015-12-01",
                          "2016-12-01","2017-12-01","2018-12-01","2019-12-01","2020-12-01","2021-12-01","2022-12-01")), alpha = .5,
             linetype = "dotted")+
  scale_fill_manual(breaks = c("Lagoon", "Tributary"), 
                     values = c("#7570B3","#66A61E"), 
                     labels = c("Lagoon prediction", "Tributary prediction"))+
  scale_color_manual(breaks = c("d18O"),
                     values = c("black"),
                     labels=(""))+
  scale_x_date(breaks = as.Date(c("2008-01-01","2009-01-01","2010-01-01","2011-01-01","2012-01-01","2013-01-01","2014-01-01","2015-01-01",
                          "2016-01-01","2017-01-01","2018-01-01","2019-01-01","2020-01-01","2021-01-01","2022-01-01")),
               labels = c(as.character(c(2008:2022))),
               limits = c(min(Pikeyears$date), max(Pikeyears$date)))+
  scale_y_continuous(limits = c(-9, -1.5),
                     breaks = c(-9,-8,-7,-6,-5,-4,-3,-2))+
  labs(y = expression(delta^18*"O"["Water/Otolith"]~("VPDB \u2030")),
       fill = expression("predicted"~delta^18*"O"["otolith"]~("VPDB \u2030")~":"),
       color=expression("interpolated"~delta^18*"O"["Water"]~("VPDB \u2030")~":"))+
  theme_classic()+theme(panel.grid.major.y = element_line(size = .3),
        panel.border = element_rect(fill = NA, size = .3),
        plot.margin = margin(c(20,10,1,1)),
        axis.text.x = element_text(color = "transparent", size = 15, angle = 90),
        axis.text.y = element_text(color = "black", size = 15),
        axis.ticks.x = element_line(colour = "transparent"),
        axis.ticks.y = element_line(size = 0.3),
        axis.ticks.length.y = unit(0.05, "cm"),
        axis.title.x = element_text(size = 15, color = "transparent"),
        axis.title.y = element_text(size = 15, color = "black"),
        axis.line = element_line(size = 0.3),
        legend.text = element_text(size = 15, color = "black"),
        legend.title = element_text(size = 15, color = "black"),
        legend.position = "bottom")+
  guides(color=guide_legend(nrow = 2, keyheight = unit(.01, "cm"), keywidth = unit(1, "cm")),
         fill=guide_legend(nrow = 2))

#Plot pike values
Obs.vs.pred <- ggplot()+
  geom_line(data=Pikeyears, aes(date, d18O, color=area, lty = "d18O"), size = 1)+
  geom_line(data=Pikeyears, aes(date, d18O_cor, color=area, lty = "d18O_cor"), size = 1)+
  geom_vline(xintercept = as.Date(c("2008-12-01","2009-12-01","2010-12-01","2011-12-01","2012-12-01","2013-12-01","2014-12-01","2015-12-01",
                          "2016-12-01","2017-12-01","2018-12-01","2019-12-01","2020-12-01","2021-12-01","2022-12-01")), alpha = .5,
             linetype = "dotted")+
  scale_fill_manual(breaks = c("Lagoon", "Tributary"), 
                     values = c("#7570B3","#66A61E"), 
                     labels = c("Lagoon prediction", "Tributary prediction"))+
  scale_color_manual(breaks = c("Lagoon","freshwater"),
                     values = c("#7570B3", "#66A61E"),
                     labels = c("Lagoon", "Tributary"))+
  scale_linetype_manual(breaks = c("d18O", "d18O_cor"),
                        values = c("solid", "dotted"),
                        labels = c("measured", "corrected"))+
  scale_x_date(breaks = as.Date(c("2008-06-01", "2008-12-01","2009-12-01", "2009-06-01","2010-12-01", 
                                  "2010-06-01","2011-12-01", "2011-06-01","2012-12-01","2012-06-01",
                                  "2013-12-01", "2013-06-01","2014-12-01", "2014-06-01","2015-12-01", 
                                  "2015-06-01", "2016-12-01", "2016-06-01","2017-12-01", "2017-06-01",
                                  "2018-12-01", "2018-06-01","2019-12-01", "2019-06-01","2020-12-01", 
                                  "2020-06-01","2021-12-01","2021-06-01","2022-12-01", "2022-06-01")),
               labels = c("Summer 08", "Winter 08","Winter 09", "Summer 09","Winter 10", "Summer 10",
                          "Winter 11", "Summer 11","Winter 12", "Summer 12","Winter 13", "Summer 13",
                          "Winter 14", "Summer 14","Winter 15", "Summer 15", "Winter 16", "Summer 16",
                          "Winter 17", "Summer 17","Winter 18", "Summer 18","Winter 19", "Summer 19",
                          "Winter 20", "Summer 20","Winter 21", "Summer 21","Winter 22", "Summer 22"),
               limits = c(min(Pikeyears$date), max(Pikeyears$date)))+
  scale_y_continuous(limits = c(-9, -1.5),
                     breaks = c(-9,-8,-7,-6,-5,-4,-3,-2))+
  labs(x = "", y = expression(delta^18*"O"["otolith"]~("VPDB \u2030")), 
       fill = expression("predicted"~delta^18*"O"["otolith"]~("VPDB \u2030")~":"),
       color="area: ",
       linetype = "")+
  theme_classic()+
  theme(panel.grid.major.y = element_line(size = .3),
        panel.border = element_rect(fill = NA, size = .3),
        plot.margin = margin(c(20,10,1,1)),
        axis.text.x = element_text(color = "black", size = 15, angle = 90),
        axis.text.y = element_text(color = "black", size = 15),
        axis.ticks.x = element_line(colour = "black"),
        axis.ticks.y = element_line(size = 0.3),
        axis.ticks.length.y = unit(0.05, "cm"),
        axis.title = element_text(size = 15, color = "black"),
        axis.line = element_line(size = 0.3),
        legend.text = element_text(size = 15, color = "black"),
        legend.title = element_text(size = 15, color = "black"),
        legend.position = "bottom")

allplot <- align_plots(Temperature, Isotopes, Obs.vs.pred, align = "v")

png(filename = "Figures/Yearly-signal-d18O_adapted.png", width = 7000, height = 9000, res = 600)
ggarrange(Temperature, Isotopes, Obs.vs.pred, nrow = 3, ncol = 1, labels = c("A)", "B)", "C)"))
dev.off()
```








